name: test-tblis-rs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-dynamic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: update submodules
        run: |
          git submodule update  --init --recursive --remote -f
      - name: run tests directly
        run: |
          cd tblis
          cargo test --test "*" --features="tblis-src/build_from_source" -- --nocapture
