name: test-tblis-src

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-dynamic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run tests directly
        run: |
          cd tblis-src
          cargo test --test "*" -vv --features="build_from_source" -- --nocapture
